### ISSUE TITLE
Generate graph visualization of the pipelines

### ISSUE THREAD

**Issue by SHuang-Broad** [broadinstitute/long-read-pipelines#148]
As we clean up and document the WDLs, it'll be good to have a graph/DAG visualization of workflows.

This helps 

  * new users understand the status of the pipeline, and 
  * developers maintain the repo as clean as possible (e.g. there are pipelines that we may not need anymore, or repeated tasks)

**Comment by kvg** [comment]
Apparently, this is a feature provided by Terra.  Since that's where GP/TAG will be using these workflows, I think we can consider this issue satisfied.

![long-read-pipelines_main](https://user-images.githubusercontent.com/2800374/95155033-38236d00-0761-11eb-8142-fbccc6718456.png)
