### ISSUE TITLE
Master build has been failing since Saturday [2020-08-02] on GPU-related pipelines

### ISSUE THREAD

**Issue by SHuang-Broad** [broadinstitute/long-read-pipelines#157]
[E.g.](https://github.com/broadinstitute/long-read-pipelines/commit/f0a4c3c02a58e6813f380704d5ef76291da351ae/checks). Tests related to `medata`, `racon`, and `guppy` fail.

**Comment by SHuang-Broad** [comment]
Turns out this most likely is an GCP issue, which has been reported and should be fixed in a day.
We'll see tonight.

**Comment by SHuang-Broad** [comment]
Looks like Google fixed it.

**Comment by kvg** [comment]
Thanks for reporting this issue to Google!
