### ISSUE TITLE
Decide on code formatting standards

### ISSUE THREAD

**Issue by SHuang-Broad** [broadinstitute/long-read-pipelines#17]
We now have code written in 
* WDL
* shell
* python

And sooner or later there could be more.
We need to think about picking a style guide.

For WDL, there's the [WDL Guidelines for GATK Repo](https://docs.google.com/document/d/1uiapGNu4lWTmiV_xHjvDfHuDMYxTpG229gqNutQQhfQ); 
for shell scripts I generally use Sublime + SublimeLinter + shellcheck; 
for python, there's the generally accepted [PEP 8](https://www.python.org/dev/peps/pep-0008/).

**Comment by SHuang-Broad** [comment]
For WDL
  * should we use tabs vs spaces
  * if using spaces, should we use 2 or 4

**Comment by kvg** [comment]
We should come up with standards for Docker images as well.  For example, make sure installed tools reside on the PATH.  I just tripped myself up with two docker images of mine that had the same tool installed, but in different locations, and that seems silly.

**Comment by SHuang-Broad** [comment]
Agree.
Regarding dockers, I actually prefer not aggregating tools into a single docker, unless it is something very very basic like `samtools`, `gsutils`, etc.
And when the pipeline gets complicated, the docker DAG gets complicated as well, but I have a way to manage that to balance out build time, docker size (not that big of a deal for long reads yet because we won't have 10k samples), and complexity.

**Comment by kvg** [comment]
I think we've more or less converged on decent rules for our WDL files and Docker images.

WDL:
  - spaces, not tabs
  - tab = 4 spaces

Docker images:
  - prefer many small images over monolithic images
  - prefer standalone images over bunch of images that depend on each other and need to be built in a specific order to function properly

**Comment by SHuang-Broad** [comment]
I'd vote for codifying these in a document.
I'll draft another document for this.
