### ISSUE TITLE
GetRunInfo should demand greater specificity for inputs

### ISSUE THREAD

**Issue by kvg** [broadinstitute/long-read-pipelines#174]
Right now, the GetRunInfo task recurses through subdirectories and finds any *.subreads.bam files that might be available for processing.  This is potentially troublesome as the user may not intend for certain files to be processed.  Instead, GetRunInfo should require specific input directories to be specified, and not recurse down them.

Note that this change may require every input JSON to be modified accordingly.  Thus this is likely a test-breaking change and would require that the minor version number of the repo be incremented.

**Comment by SHuang-Broad** [comment]
fixed
