### ISSUE TITLE
How does one handle "reworked" samples

### ISSUE THREAD

**Issue by SHuang-Broad** [broadinstitute/long-read-pipelines#180]
Occasionally, the lab side has to "rework" on a sample for various reasons, but one tricky part of this is that the `SM` section of the header will be different for bams generated by the alignment workflow in our current pipeline. For example

```
@RG	ID:PAE07691.2-A1-D1.1a751697	SM:SM-J1Y5M	PL:ONT	PU:PC48A003	DT:2019-10-28T17:04:27.181915+00:00
@RG	ID:PAE17582.1-E9-H9.295697e7	SM:SM-J1Y5M_RW	PL:ONT	PU:PC48A003	DT:2019-11-25T17:00:02.585349+00:00
```

This has an implication for downstream analysis hence should be addressed when the workflow for merging such "reworked" sequences with the original, i.e. a simple `samtools merge` won't do it, and at least a `reheader` step is needed.

**Comment by kvg** [comment]
This can be handled upfront in the input JSON: the sample name that's detected automatically can be optionally overridden by manual specification before processing begins.  Is that sufficient to address this issue, or do you think we need an additional way of fixing this?

**Comment by SHuang-Broad** [comment]
What kind of manual override are you referring to?
I looked at the ONT single cell pipeline WDL and currently it does not allow specifying sample names.
`AlignReads.wdl` takes an argument to `-R` for samtools, so that's where read group information is settled.

**Comment by kvg** [comment]
The ONT single cell pipeline or the ONT whole genome pipeline?  This is what the ONTWholeGenomeSingleFlowcell pipeline has:

```
workflow ONTWholeGenomeSingleFlowcell {
    input {
        String raw_reads_gcs_bucket
        **String? sample_name**

        File ref_fasta
        File ref_fasta_fai
        File ref_dict

        File tandem_repeat_bed
        File ref_flat
        File dbsnp_vcf
        File dbsnp_tbi

        String mt_chr_name
        File metrics_locus

        String gcs_out_root_dir
    }

    String outdir = sub(gcs_out_root_dir, "/$", "")

    call ONT.FindSequencingSummaryFiles { input: gcs_input_dir = raw_reads_gcs_bucket}

    scatter (summary_file in FindSequencingSummaryFiles.summary_files) {
        call ONT.GetRunInfo { input: summary_file = summary_file }
        call ONT.ListFiles as ListFast5s { input: summary_file = summary_file, suffix = "fast5" }
        call ONT.ListFiles as ListFastqs { input: summary_file = summary_file, suffix = "fastq" }

        **String SM  = select_first([sample_name, GetRunInfo.run_info["sample_id"]])**
        String PL  = "ONT"
        String PU  = GetRunInfo.run_info["instrument"]
        String DT  = GetRunInfo.run_info["started"]
        String ID  = GetRunInfo.run_info["flow_cell_id"] + "." + GetRunInfo.run_info["position"]
        String DIR = GetRunInfo.run_info["protocol_group_id"] + "." + SM + "." + ID
        String SID = ID + "." + sub(GetRunInfo.run_info["protocol_run_id"], "-.*", "")
        String RG = "@RG\\tID:~{SID}\\tSM:~{SM}\\tPL:~{PL}\\tPU:~{PU}\\tDT:~{DT}"
```

This idiom is quite useful in being able to override an autodetected sample name.  The read group definition that is taken by AlignReads is populated here with the overridden sample in place.

**Comment by kvg** [comment]
(Drat, the formatting apparently doesn't work in code mode.  Look for the double-asterisks for what I highlighted.)

**Comment by SHuang-Broad** [comment]
I don't know how I missed that. :see_no_evil:

**Comment by kvg** [comment]
Should we close this or do you still foresee a need for a new/additional merging tool?

**Comment by SHuang-Broad** [comment]
closing (remark on stupidity remains :stuck_out_tongue:)
