### ISSUE TITLE
Better organize tests for scripts

### ISSUE THREAD

**Issue by SHuang-Broad** [broadinstitute/long-read-pipelines#189]
We currently have scripts that provide non-trivial functionalities, but they are not yet heavy enough to warrant a full blown repo or integration into another toolkit like GATK.

These scripts need to be tested.

So we need to have a structure for that.

**Comment by SHuang-Broad** [comment]
Topics to handle:

- [ ] where to put test data
- [ ] directory structure
- [ ] naming scheme

**Comment by kvg** [comment]
In response to this, we now have tox testing for scripts that implement non-trivial functionality in the workflows.

Directory structure is as follows:

```
test
├── test_data
│   └── for_scripts
│       ├── consensus.bam
│       ├── shard_bam_test_file.bam
│       ├── shard_bam_test_file.bam.pbi
│       └── subreads.bam
├── test_json
│   ├── CanuRunner.test.json
│   ├── DownloadFromFTP.test.json
│   ├── GuppyRunner.test.json
│   ├── MedakaRunner.test.json
│   ├── NanopolishRunner.test.json
│   ├── ONT10xSingleFlowcell.test.json
│   ├── ONTWholeGenomeSingleFlowcell.test.json
│   ├── PBCCSDemultiplexOnlySingleFlowcell.test.tiny_file.json
│   ├── PBCCSIndividualZMWsSingleFlowcell.test.json
│   ├── PBCCSOnlySingleFlowcell.test.ChrMAndChr20SubsetGRCh38.json
│   ├── PBCCSWholeGenomeSingleFlowcell.test.ChrMAndChr20SubsetGRCh38.json
│   ├── RaconRunner.test.json
│   ├── TestCromwell.json
│   └── all_disabled_tests.txt
└── test_scripts
    ├── test_extract_uncorrected_reads.py
    └── test_shard_bam.py
```

Test data for the tests goes in 'test/test_data/for_scripts'.  The naming scheme for tests is for them to take on the name of the original script with a "test_" prefix.

Follow the examples in the tox.ini file to add the test to the list of tests to be run automatically when tox is invoked.

**Comment by SHuang-Broad** [comment]
@kvg mind having a mini wiki page for this? Or a section for developers in the readme?
