### ISSUE TITLE
detect_run_info.py fails when run files are in base of bucket

### ISSUE THREAD

**Issue by yuliamostovoy** [broadinstitute/long-read-pipelines#219]
Running PBFlowcell.wdl with bam files that are in the base directory of the google bucket results in this error:

`python /usr/local/bin/detect_run_info.py --SM C57BL6J gs://fc-6d260212-9bd9-420e-8850-0167d9c4c74b/

Traceback (most recent call last):
  File "/usr/local/bin/detect_run_info.py", line 52, in \<module\>
    if prefix[-1] != delimiter:
IndexError: string index out of range`

**Comment by kvg** [comment]
Hi Yulia - I just realized I was wrong when we spoke earlier.  This script wants the full path to the BAM file, rather than the directory.  Can you see if it works if you run it as follows?

```
$ python3 docker/lr-pb/detect_run_info.py --SM C57BL6J gs://fc-6d260212-9bd9-420e-8850-0167d9c4c74b/m64019_200601_092433.subreads.bam
```

Or if this happening when you run one of the workflows that calls this script?

**Comment by kvg** [comment]
Thanks for the report, Yulia!  I've just pushed a fix and the Dockstore/Terra endpoints should be automatically updated in a few minutes.  Please let me know if that does or doesn't work for you.

**Comment by yuliamostovoy** [comment]
Looks like it's working, thanks!
