### ISSUE TITLE
pbindex requires integer read groups

### ISSUE THREAD

**Issue by jonn-smith** [broadinstitute/long-read-pipelines#220]
The latest version of PacBio's tools (10.0) requires that read groups are primarily integer based.

This is reflected in their documentation:

https://pacbiofileformats.readthedocs.io/en/10.0/PacBioBamIndex.html

As a result, when we rename read groups in the pipelines `pbindex` will no longer work properly.

**Comment by SHuang-Broad** [comment]
fixed in main
