### ISSUE TITLE
Have a task for correcting @RG line of swapped PacBio samples

### ISSUE THREAD

**Issue by SHuang-Broad** [broadinstitute/long-read-pipelines#286]
The input bam to pipelines, regardless of sequencing type, have its `SM` information and `LB` information derived from the metadata when sequenced.

Therefore if the lab put in the incorrect metadata, the BAM inherits that, and this throws off a many outputs (at minimum, the SM line is wrong).

So we should think about how to fix this.

@kvg this is very important, and we could either fix it in the Terra table management system, or have a standalone WDL task for that.

**Comment by kvg** [comment]
Good catch. Maybe as an interim (albeit expensive) fix, we should just rerun workflows for flowcells/samples who have had metadata updated?

**Comment by SHuang-Broad** [comment]
Yes, I already have a branch that's almost working, with a catch, it only fix that from the alignment downwards.

Checking which ones have unmatched sample info isn't hard with FISS. There shouldn't be many, so won't be that expensive.
