### ISSUE TITLE
`resources/gcs_workflow_options.json` might be out of date

### ISSUE THREAD

**Issue by SHuang-Broad** [broadinstitute/long-read-pipelines#46]
Got the following error running on methods Cromwell 45.

```
Unable to find block device for filesystem /dev/disk/by-id/google-local-disk.
```

Googling landed on [this](https://github.com/broadinstitute/cromwell/issues/4388) still open ticket.

**Comment by kvg** [comment]
Determined that this was a monitoring script warning and not an issue affecting our work.  Also our workflow options have evolved considerably since this was opened.
