### ISSUE TITLE
optimize TrioBinChildLongReads workflow

### ISSUE THREAD

**Issue by SHuang-Broad** [broadinstitute/long-read-pipelines#47]
One obvious optimization is to localize only needed parental reads in the meryl-count step.

**Comment by SHuang-Broad** [comment]
Ooops, created several hours too early.
Wait for the PR tomorrow.

**Comment by SHuang-Broad** [comment]
Another one, based on the timing [here](https://cromwell-v47.dsde-methods.broadinstitute.org/api/workflows/v1/e432bd48-5b2b-455f-b42e-344f7e654ee7/timing) is to speed up the parental reads re-partition task, which currently takes over 1/3 of the 12 hour runtime.

**Comment by SHuang-Broad** [comment]
To provide some data that can help us make decisions on which parts to optimize

![triobin cost](https://user-images.githubusercontent.com/16310888/68913304-d4e3b300-0728-11ea-9a22-bdfe3e6c509f.jpg)

**Comment by SHuang-Broad** [comment]
The new implementation proposed by #51 is going to lower cost by ~ 50%.
Attatched are two cost breakdowns. Apparently at the cost of slightly more expensive parental reads re-partition (from ~$0.30 to ~ $1.10), the cost of meryl count is brought down significantly.

![944e240a-f9d9-4fd6-8e2b-0d28a28e9d17 cost](https://user-images.githubusercontent.com/16310888/69501337-06e7d880-0ed2-11ea-9c94-1496b2b2a574.jpg)
![b409e62a-86a9-409a-b447-39a386b55aa3 cost](https://user-images.githubusercontent.com/16310888/69501338-06e7d880-0ed2-11ea-90d3-7d8fad2d67c8.jpg)

**Comment by SHuang-Broad** [comment]
Based on two new runs with different test trios, it might be better to have less number of input parental short read `fastq`'s (i.e. larger files), but smaller chunks of child long read files.
[here](https://cromwell-v45.dsde-methods.broadinstitute.org/api/workflows/v1/0ddd5e0f-d7d0-4475-aabd-b8d57006e8ba/timing)
and
[here](https://cromwell-v47.dsde-methods.broadinstitute.org/api/workflows/v1/e0a56948-5eef-4921-bd44-f93dda851778/timing)

**Comment by SHuang-Broad** [comment]
Another TODO:

While working on decreasing the fraction of un-assigned child long reads by using a `$k$ = 31` instead of 21, the runtime resources allocated were discovered to be low for multiple stages.

This is falls under the general quest to adjust runtime resources to known input parameters (`$k$, expected coverage).

**Comment by kvg** [comment]
Now sufficiently optimized for our current needs.
