### ISSUE TITLE
Change to dockerhub

### ISSUE THREAD

**Issue by kvg** [broadinstitute/long-read-pipelines#5]
Right now the pipeline Docker images all exist in our personal Docker sites.  Let's move these to Dockerhub.

**Comment by SHuang-Broad** [comment]
If dockers can be public (for whatever reasons, some dockers might need to be private), we can also put them [here](https://console.cloud.google.com/gcr/images/broad-dsde-methods/GLOBAL?project=broad-dsde-methods&folder&organizationId=548622027621)

**Comment by kvg** [comment]
All of the Docker images have been moved to https://quay.io/organization/broad-long-read-pipelines .
