### ISSUE TITLE
Watchout for alignments with > 65535 CIGAR operations

### ISSUE THREAD

**Issue by SHuang-Broad** [broadinstitute/long-read-pipelines#59]
As the reads and assemblies gets longer, we will get there.
In fact we might already be there for some assemblies with NG50 > 10Mb.

See minimap2's comment about how to do that.

A tricky thing is how up-to-date downstream tools are, when it comes to adhering to the [hts-specs](https://github.com/samtools/hts-specs/pull/227).

**Comment by SHuang-Broad** [comment]
The alignment workflow now turns on `-L` by default.
We are unsure if the downstream tools are aware of the `CG` tag yet.

**Comment by kvg** [comment]
I may have broken this when the merge of the kvg_ont_fixes branch into master.  We should update the AlignReads.Minimap2 task.

**Comment by kvg** [comment]
Done - by default we now supply the -L argument to minimap2, which writes long cigar strings to a special tag.
