### ISSUE TITLE
Investigate if we should `tar` some of the result folders when using cromwell

### ISSUE THREAD

**Issue by SHuang-Broad** [broadinstitute/long-read-pipelines#61]
Relying on cromwell for delocalizing a folder gives you names like 
`glob-4474304f3e3392228593ba19c5cd74e8`,
`glob-de84a38a722f40d0a73061d4179b1788`
which takes an unnecessary effort to decode, especially when the two folders hold contents in highly similar structures.

`tar`-only avoids the compression time, hence maybe a good compromise between easy-of-comprehension and speed.

**Comment by kvg** [comment]
Decided to leave this as an individual developer's decision when the situation arises.
