### ISSUE TITLE
Pipeline regression testing

### ISSUE THREAD

**Issue by kvg** [broadinstitute/long-read-pipelines#7]
How are we going to verify that this pipeline continues to function the way we expect as we add things to it over time?

**Comment by SHuang-Broad** [comment]
One issue to decide is granularity.
We cannot have unit tests like GATK.
But we need at least integration tests.

For the moment, what about:
when one wants to merge a new workflow, she/he needs to provide an integration test.
when one wants to update an existing workflow, integration test result should be provided in the PR.

We need a test engineer...

**Comment by kvg** [comment]
Done - we now have a custom CI server running checking on every push to any branch, and a nightly test on master.
