### ISSUE TITLE
Inventory codebase to identify and remove redundant functionality

### ISSUE THREAD

**Issue by kvg** [broadinstitute/long-read-pipelines#73]
We now have a few WDLs that have some tasks that are slightly or entirely redundant with other WDLs.  We should inventory the codebase to see where we have multiple tasks that do nearly the same thing, and then make a plan to consolidate those tasks into one canonical task.

**Comment by kvg** [comment]
I think we're doing pretty well for this now, but it'll be ongoing work.

**Comment by SHuang-Broad** [comment]
Maintain.
Utils is always the primary suspect when it comes duplicated efforts.

**Comment by kvg** [comment]
Done.  We'll have to keep vigilant on this, but right now there appears to be little redundancy across the codebase.
