### ISSUE TITLE
Have a plan for docker image versioning

### ISSUE THREAD

**Issue by SHuang-Broad** [broadinstitute/long-read-pipelines#77]
The utils docker is going to be the hardest to figure out.

**Comment by kvg** [comment]
Done - I've fixed all the versioning and we can continue from where we are using semantic versioning (https://semver.org/).  I'm also currently pushing the docker images to both quay.io and gcr.io .  We don't need to switch over to gcr.io just yet, but we probably should at some point in the near future.

**Comment by SHuang-Broad** [comment]
What I meant was a more automated version: if a dockerfile is touched, corresponding WDLs need to be synced as well.
Does #110 do that?

**Comment by kvg** [comment]
Agreed upon in the review party - we'll close this issue for now; I don't think we want to break call caching for in-development workflows, and we probably don't need this level of sophistication just yet for minor/major version increases of the repo.
