### ISSUE TITLE
Remove non-code directories

### ISSUE THREAD

**Issue by SHuang-Broad** [broadinstitute/long-read-pipelines#89]
Let's keep data and reports somewhere else, and make this repo code only.

**Comment by kvg** [comment]
Maybe we should move all the input JSONs to a separate private repo?

**Comment by SHuang-Broad** [comment]
That'd be great.

Although, I feel like we are tacking a bigger problem, that Terra is trying solve:
how do you nicely connect code and input/specification, yet keep them separately maintained?

**Comment by SHuang-Broad** [comment]
But it's not an easy task to make iterations to the workflow now in Terra, per my understanding.
So I'd vote for what you suggested, move the data and reports dir to some other place with appropriate access control.

**Comment by kvg** [comment]
Yeah, though we will need to leave workflow test JSONs behind.  Having a test JSON for a workflow you're importing seems to be a Dockstore requirement.

**Comment by SHuang-Broad** [comment]
I'd say that's not a bad requirement (well there are multiple aspects of this), in the sense that at least there's a test (assuming it doesn't give a false sense of security).

And it is not conflicting with #7.

**Comment by kvg** [comment]
Done.  This codebase now only contains workflow code and test specifications, and is suitable for any group (inside and outside the Broad) to use.  The production input JSONs are now in a separate repo.
