### ISSUE TITLE
Experiment with major assembly polishers

### ISSUE THREAD

**Issue by SHuang-Broad** [broadinstitute/long-read-pipelines#94]
Racon, Medaka, MarginPolish+HELEN.
And maybe more.

Result with Racon seems interesting.

**Comment by kvg** [comment]
How is "interesting" defined?

**Comment by SHuang-Broad** [comment]
* GPU acceleration seems slow down one step slightly, but significantly speeds up another step.
* The resulting assembly was polished to be quite a bit longer than the original, suggesting many indel errors in the original assembly, assuming the polish made the assembly better in indel rate.

**Comment by SHuang-Broad** [comment]
@ericsong @kvg should this be closed (or replaced with another ticket) given recent PRs?

**Comment by ericsong** [comment]
Are there others we'd like to add? Right now, we have Nanopolish, Racon, and Medaka.

**Comment by SHuang-Broad** [comment]
That's all that I know of. 
Any others, @kvg ?

**Comment by ericsong** [comment]
I'm interested in trying out MarginPolish so I'll add that as well and close this issue.

**Comment by kvg** [comment]
We've found satisfactory answers to this on malaria data, but we should be mindful that different recipes have difference performances on different genomes.  We'll likely need to evaluate polishing procedures quite often for different organisms.
